"""add Department

Revision ID: 395075facccd
Revises: 3d21e8cf1e14
Create Date: 2025-09-14 22:34:18.178059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '395075facccd'
down_revision = '3d21e8cf1e14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('department')
    # ### end Alembic commands ###
